### PR TITLE
Xbox interface

### PR DESCRIPTION
**Pull request by b23prodtm**

### CODE REVIEW

**Comment by Axadiw** [comment]
Thanks for the update, I'll review this PR soon :)

**Comment by b23prodtm** [comment]
Alright ! Thanks for the feedback!

**Comment by Axadiw** [comment]
Damn, I've merged this by mistake...

Anyway, could you include "....\vJoy\x64\Release-Xbox\VboxWrap.dll" file, because it isn't available in the repo, and I can't compile your PR

**Comment by b23prodtm** [comment]
Alright ! Here you are. Just uploaded the libraries Into MFIGamepadShared folder.

**Comment by Axadiw** [comment]
Ok, I've noticed 

```
VboxWrap.dll
vJoyInterface.dll
```

in your repo, but could you add source code as well?

**Comment by b23prodtm** [comment]
Do you need the vjoy source code you mean? I'm on the Xbox-CLR-wrapper branch at my own forked repo of vJoy.

**Comment by Axadiw** [comment]
Ok, I'll check your code on this "Xbox-CLR-wrapper" branch than.

I've been looking for this IWrapper class everywhere, and I couldn't find it. That why I'm asking  ;)

**Pull request merged**
